service: blockconvey-main-website-nextjs
runtime: nodejs20
instance_class: F4_1G

automatic_scaling:
  target_cpu_utilization: 0.85
  min_instances: 1
  max_instances: 10

env: standard

entrypoint: npm run start

env_variables:
  NODE_ENV: production
  NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyAfe6vLmhpFxch7F1S7_IN2pnFjvKB54Ic"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "block-convey---blog.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "block-convey---blog"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "block-convey---blog.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "930903797002"
  NEXT_PUBLIC_FIREBASE_APP_ID: "1:930903797002:web:75bfaa696b2115bc3f1ef3"
